name: support
description: Support

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 0.2.1+19

environment:
  sdk: ">=2.17.3 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  # A
  agora_rtc_engine: ^5.3.0

  # B

  # C
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3

  # D
  dio: 5.1.1

  # E
  extended_image: ^7.0.2
  # emoji_picker_flutter: ^1.3.0

  # F
  firebase_core: ^2.4.1
  firebase_auth: ^4.4.2
  flutter_rating_bar: ^4.0.1
  firebase_messaging: ^14.2.1
  # flutter_chat_bubble: ^2.0.0
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^13.0.0
  firebase_crashlytics: ^3.0.9
  firebase_storage: ^11.0.10
  fluttertoast: ^8.2.1
  avatar_glow: ^2.0.2

  # G
  google_fonts: ^4.0.3
  get: ^4.6.5

  # H

  # I
  intl_phone_field: ^3.1.0

  # P
  pin_code_fields: ^7.4.0
  permission_handler: ^10.2.0
  percent_indicator: ^4.2.3

  # R
  razorpay_flutter: ^1.3.4

  # S
  shared_preferences: ^2.1.0
  stop_watch_timer: ^1.5.0
  shimmer: ^2.0.0
  share_plus: ^6.3.2

  url_launcher: ^6.1.10


  just_audio: ^0.9.32
  audioplayers: ^3.0.1

  image_picker: ^0.8.7+1
  timeago_flutter: ^1.2.0
  cloud_firestore: ^4.3.1
  device_info_plus: ^4.0.1
  intl: ^0.17.0
  http: ^0.13.5

  pull_to_refresh: ^2.0.0
  flutter_ringtone_player: ^3.2.0
  # flutter_windowmanager: ^0.2.0
  in_app_update: ^4.0.1
  swipe_to: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/sound/

